language: generic

dist: focal

sudo: required

cache:
  directories:
    - $HOME/.cache
    - /opt/cloudera

env:
  global:
    - CLOUDERA_MANAGER_VERSION=7.4.4
    - CDH_VERSION=6.3.2
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - HADOOP_HOME=/opt/cloudera/parcels/CDH/lib/hadoop
    - HADOOP_CONF_DIR=/etc/hadoop/conf

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - sudo apt-get install -y wget curl

install:
  - wget https://archive.cloudera.com/cm7/${CLOUDERA_MANAGER_VERSION}/ubuntu2004/apt/cloudera-manager.list
  - sudo cp cloudera-manager.list /etc/apt/sources.list.d/
  - wget https://archive.cloudera.com/cm7/${CLOUDERA_MANAGER_VERSION}/ubuntu2004/apt/archive.key
  - sudo apt-key add archive.key
  - sudo apt-get update
  - sudo apt-get install -y cloudera-manager-agent
  - sudo mkdir -p /opt/cloudera/parcels
  - sudo mkdir -p /etc/hadoop/conf
  - sudo mkdir -p /var/log/cloudera-scm-agent
  - sudo chown -R $USER:$USER /opt/cloudera
  - sudo chown -R $USER:$USER /var/log/cloudera-scm-agent

before_script:
  - echo '<?xml version="1.0"?><configuration></configuration>' | sudo tee /etc/hadoop/conf/core-site.xml
  - echo '<?xml version="1.0"?><configuration></configuration>' | sudo tee /etc/hadoop/conf/hdfs-site.xml
  - echo '<?xml version="1.0"?><configuration></configuration>' | sudo tee /etc/hadoop/conf/mapred-site.xml
  - echo '<?xml version="1.0"?><configuration></configuration>' | sudo tee /etc/hadoop/conf/yarn-site.xml
  - export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

script:
  - java -version
  - cloudera-scm-agent --version || echo "CM Agent not fully configured (expected in CI)"
  - ls -la /opt/cloudera/
  - ls -la /etc/hadoop/conf/
  - python3 -c "
    import xml.etree.ElementTree as ET;
    tree = ET.parse('/etc/hadoop/conf/core-site.xml');
    print('core-site.xml is valid XML')"
  - docker --version

matrix:
  include:
    - name: "Basic Cloudera Setup"
      env: TEST_TYPE=basic
    - name: "Cloudera with Docker"
      env: TEST_TYPE=docker
      script:
        - docker pull cloudera/quickstart:latest || echo "Docker image not available"
        - echo "Docker-based Cloudera testing complete"

after_success:
  - echo "Cloudera CI pipeline completed successfully"
  
after_failure:
  - echo "Cloudera CI pipeline failed"
  - cat /var/log/cloudera-scm-agent/cloudera-scm-agent.log || echo "No agent log found"

after_script:
  - sudo service cloudera-scm-agent stop || echo "Agent not running"

notifications:
  email:
    on_success: change
    on_failure: always
