language: generic
dist: focal
sudo: required
cache:
  directories:
    - $HOME/.cache
    - /opt/cloudera
env:
  global:
    - CLOUDERA_MANAGER_VERSION=7.4.4
    - CDH_VERSION=6.3.2
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - HADOOP_HOME=/opt/cloudera/parcels/CDH/lib/hadoop
    - HADOOP_CONF_DIR=/etc/hadoop/conf
services:
  - docker
before_install:
  - chmod +x scripts/*.sh # chmod everything insight. 
  - ./scripts/setup_system.sh
install:
  - ./scripts/install_cloudera.sh
before_script:
  - ./scripts/configure_hadoop.sh
script:
  - ./scripts/run_tests.sh
matrix:
  include:
    - name: "basic cloudera setup"
      env: TEST_TYPE=basic
    - name: "cloudera with docker"
      env: TEST_TYPE=docker
      script:
        - ./scripts/run_docker_tests.sh
after_success:
  - ./scripts/cleanup.sh success
after_failure:
  - ./scripts/cleanup.sh failure
